#!/bin/bash
# AWS Deployment Checklist - Print this out or check it off as you go
# Created: February 2026

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  AWS DEPLOYMENT CHECKLIST - Business Online Application        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Print this file or follow along in your terminal:"
echo "  grep -A 200 'PREPARATION' AWS_DEPLOYMENT_CHECKLIST.md"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 1: PREPARATION (Before AWS)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Read AWS_DEPLOYMENT_SUMMARY.md (5 minutes)"
echo "      Goal: Understand what has been created"
echo ""
echo "  [ ] Read AWS_DEPLOYMENT_QUICKSTART.md (15 minutes)"
echo "      Goal: Understand the 5-step process"
echo ""
echo "  [ ] Review AWS_DEPLOYMENT_GUIDE.md sections you need"
echo "      Goal: Deep dive on your chosen option"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 2: AWS SETUP (5-10 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Create AWS account (https://aws.amazon.com)"
echo "      Task: Sign up with email & payment method"
echo ""
echo "  [ ] Create IAM user with programmatic access"
echo "      Tasks:"
echo "        - Go to AWS Console → IAM → Users"
echo "        - Create new user with 'Access key - Programmatic access'"
echo "        - Attach policies:"
echo "          * AmazonElasticBeanstalkFullAccess"
echo "          * AmazonEC2ContainerRegistryFullAccess"
echo "          * AmazonECS_FullAccess"
echo "          * AmazonRDSFullAccess"
echo ""
echo "  [ ] Install AWS CLI"
echo "      Command:"
echo "        curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\""
echo "        unzip awscliv2.zip"
echo "        sudo ./aws/install"
echo ""
echo "  [ ] Configure AWS CLI"
echo "      Command: aws configure"
echo "      Enter:"
echo "        - Access Key ID (from IAM user)"
echo "        - Secret Access Key (from IAM user)"
echo "        - Default region: us-east-1"
echo "        - Default output: json"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 3: DATABASE SETUP (5-10 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Create RDS MySQL database"
echo "      Option A: Using AWS Console"
echo "        - Go to RDS → Create database"
echo "        - Engine: MySQL 8.0"
echo "        - Instance class: db.t3.micro"
echo "        - Database name: business_online"
echo ""
echo "      Option B: Using AWS CLI"
echo "        - Run command in AWS_DEPLOYMENT_QUICKSTART.md"
echo ""
echo "  [ ] Wait for database to be available (5-10 minutes)"
echo "      Task: Monitor in AWS Console → RDS"
echo ""
echo "  [ ] Get RDS endpoint"
echo "      Command:"
echo "        aws rds describe-db-instances \\"
echo "          --db-instance-identifier businessonline-db \\"
echo "          --query 'DBInstances[0].Endpoint.Address'"
echo ""
echo "  [ ] Copy endpoint for next step"
echo "      Example: businessonline-db.xxxxx.us-east-1.rds.amazonaws.com"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 4: CONFIGURATION (5 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Copy production environment template"
echo "      Command:"
echo "        cp server/.env.production server/.env"
echo ""
echo "  [ ] Edit .env file with actual values"
echo "      Command: nano server/.env"
echo ""
echo "      Required values to set:"
echo "        - NODE_ENV=production"
echo "        - CORS_ORIGIN=https://yourdomain.com"
echo "        - MYSQL_HOST=<your-rds-endpoint>"
echo "        - MYSQL_PORT=3306"
echo "        - MYSQL_USER=admin"
echo "        - MYSQL_PASSWORD=<your-password>"
echo "        - MYSQL_DATABASE=business_online"
echo "        - FIREBASE_API_KEY=<your-key>"
echo "        - FIREBASE_AUTH_DOMAIN=<your-domain>"
echo "        - FIREBASE_PROJECT_ID=<your-project>"
echo "        - FIREBASE_STORAGE_BUCKET=<your-bucket>"
echo "        - FIREBASE_MESSAGING_SENDER_ID=<your-id>"
echo "        - FIREBASE_APP_ID=<your-app-id>"
echo ""
echo "  [ ] Verify .env file is not in git"
echo "      Command: grep '\.env' .gitignore"
echo "      Expected: Should show '.env' in output"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 5: PRE-DEPLOYMENT VERIFICATION (2 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Run pre-deployment check script"
echo "      Command: bash pre-deployment-check.sh"
echo ""
echo "  [ ] Review check results"
echo "      Looking for:"
echo "        - Green checkmarks: ✓ Good"
echo "        - Yellow warnings: ⚠ Review (not blocking)"
echo "        - Red errors: ✗ Must fix"
echo ""
echo "  [ ] Fix any critical errors"
echo "      Common issues:"
echo "        - AWS credentials not configured → Run 'aws configure'"
echo "        - Database localhost → Update to RDS endpoint"
echo "        - Missing files → Run 'npm install' first"
echo ""
echo "  [ ] Re-run check after fixes"
echo "      Command: bash pre-deployment-check.sh"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 6: CHOOSE DEPLOYMENT METHOD"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Choose one of the following three options:"
echo ""
echo "OPTION A: ELASTIC BEANSTALK (⭐ Recommended) ────────────────────"
echo ""
echo "  [ ] Easiest option - Perfect for beginners"
echo "      Command: ./deploy-to-aws.sh businessonline production us-east-1"
echo ""
echo "      This script will:"
echo "        - Build your React app"
echo "        - Create Elastic Beanstalk environment"
echo "        - Deploy application"
echo "        - Display URL when complete"
echo ""
echo "OPTION B: ECS FARGATE (Docker-based) ─────────────────────────────"
echo ""
echo "  [ ] More control over containers"
echo "      Command: ./deploy-to-ecr.sh us-east-1"
echo ""
echo "      This script will:"
echo "        - Build Docker image locally"
echo "        - Push to AWS ECR"
echo "        - Display ECR repository URL"
echo ""
echo "      Then create ECS service using the image URL"
echo ""
echo "OPTION C: EC2 + RDS (Manual) ──────────────────────────────────────"
echo ""
echo "  [ ] Maximum control, requires more manual setup"
echo "      Instructions: See AWS_DEPLOYMENT_GUIDE.md 'Option 3'"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 7: DEPLOYMENT (15-30 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Make scripts executable (if not already)"
echo "      Command: chmod +x deploy-to-aws.sh deploy-to-ecr.sh"
echo ""
echo "  [ ] Run deployment script (choose your option from Phase 6)"
echo "      Option A: ./deploy-to-aws.sh businessonline production us-east-1"
echo "      Option B: ./deploy-to-ecr.sh us-east-1"
echo ""
echo "  [ ] Monitor deployment progress"
echo "      For Elastic Beanstalk: Watch AWS Console → Elastic Beanstalk"
echo "      For ECS: Watch AWS Console → ECR for push progress"
echo ""
echo "  [ ] Wait for deployment to complete (5-15 minutes)"
echo "      Don't close terminal - let it finish"
echo ""
echo "  [ ] Note your application URL when deployment completes"
echo "      Example: https://businessonline-prod.elasticbeanstalk.com"
echo "      Or: Application Load Balancer URL for ECS"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 8: CONFIGURATION IN AWS CONSOLE (5 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Set environment variables in AWS Console"
echo "      For Elastic Beanstalk:"
echo "        - Go to AWS Console → Elastic Beanstalk"
echo "        - Select your environment"
echo "        - Configuration → Software"
echo "        - Add all environment variables from your .env file"
echo "        - Apply changes"
echo ""
echo "  [ ] Verify security groups allow database access"
echo "      Tasks:"
echo "        - Check RDS security group allows port 3306"
echo "        - Check EB/ECS security group can reach RDS"
echo ""
echo "  [ ] Set up CloudWatch alarms (optional but recommended)"
echo "      Recommended alarms:"
echo "        - High CPU (>80%)"
echo "        - High memory (>85%)"
echo "        - Database connection failures"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 9: VERIFICATION & TESTING (5-10 minutes)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Test application loads in browser"
echo "      URL: https://your-app-url"
echo "      Expected: Application loads without errors"
echo ""
echo "  [ ] Test API health endpoint"
echo "      Command: curl https://your-app-url/api/health"
echo "      Expected: Response with status 200 and health data"
echo ""
echo "  [ ] Test database connection"
echo "      - Try logging in"
echo "      - Create/edit an item"
echo "      - Verify data persists"
echo ""
echo "  [ ] Test authentication with Firebase"
echo "      - Try sign up"
echo "      - Try login"
echo "      - Try password reset"
echo ""
echo "  [ ] Check CloudWatch logs for errors"
echo "      Command: aws logs tail /aws/elasticbeanstalk/... --follow"
echo "      Or: AWS Console → CloudWatch → Logs"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 10: POST-DEPLOYMENT SETUP (Optional but Recommended)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Set up SSL certificate with ACM"
echo "      Task: Request certificate for your domain"
echo ""
echo "  [ ] Configure Route 53 DNS"
echo "      Task: Point your domain to the AWS resources"
echo ""
echo "  [ ] Set up CloudFront for static files"
echo "      Task: Create distribution for S3 bucket"
echo ""
echo "  [ ] Set up automated backups"
echo "      Command: aws rds modify-db-instance ... --backup-retention-period 30"
echo ""
echo "  [ ] Configure email notifications for alarms"
echo "      Task: Set SNS topic and subscriptions"
echo ""
echo "  [ ] Set up resource tagging for cost tracking"
echo "      Task: Add 'Environment', 'Application', 'Owner' tags"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "PHASE 11: MONITORING & OPTIMIZATION (Ongoing)"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Monitor daily for first week"
echo "      Check:"
echo "        - CloudWatch metrics"
echo "        - Logs for errors"
echo "        - Performance metrics"
echo ""
echo "  [ ] Set up cost alerts"
echo "      Task: AWS Budgets → Create budget alert"
echo "      Trigger: When spending exceeds $100/month"
echo ""
echo "  [ ] Plan scaling strategy"
echo "      Decision: When to upgrade instance size?"
echo ""
echo "  [ ] Schedule regular backups verification"
echo "      Task: Test restore from backup weekly"
echo ""
echo "  [ ] Review and optimize costs"
echo "      Task: Monthly review of AWS Console Cost Explorer"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "FINAL CHECKLIST - Application Live!"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  ✓ Application loads in browser"
echo "  ✓ API endpoints respond correctly"
echo "  ✓ Database queries work"
echo "  ✓ Authentication works"
echo "  ✓ SSL/HTTPS enabled"
echo "  ✓ CloudWatch logs showing activity"
echo "  ✓ Health checks passing"
echo "  ✓ Auto-scaling configured"
echo "  ✓ Backups scheduled"
echo "  ✓ Monitoring alarms active"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🎉 CONGRATULATIONS!"
echo "Your Business Online application is now LIVE on AWS!"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "TROUBLESHOOTING & SUPPORT"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "If something doesn't work:"
echo ""
echo "1. Check logs first:"
echo "   eb logs production -v       # For Elastic Beanstalk"
echo "   aws logs tail /ecs/... --follow  # For ECS"
echo ""
echo "2. Read relevant documentation:"
echo "   AWS_DEPLOYMENT_GUIDE.md → Troubleshooting section"
echo ""
echo "3. Common issues:"
echo "   • Application won't start → Check logs"
echo "   • Database won't connect → Check security groups"
echo "   • Slow performance → Check CloudWatch metrics"
echo "   • Cost too high → Review AWS_DEPLOYMENT_GUIDE.md cost section"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "USEFUL COMMANDS"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "# View logs"
echo "eb logs production -v"
echo ""
echo "# SSH into instance"
echo "eb ssh production"
echo ""
echo "# Open application"
echo "eb open production"
echo ""
echo "# Scale environment"
echo "eb scale 3"
echo ""
echo "# View environment status"
echo "eb status production"
echo ""
echo "# Terminate environment (if needed)"
echo "eb terminate production"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "DOCUMENTATION FILES TO KEEP HANDY"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "1. AWS_DEPLOYMENT_SUMMARY.md - Overview & checklist"
echo "2. AWS_DEPLOYMENT_QUICKSTART.md - 5-step guide"
echo "3. AWS_DEPLOYMENT_GUIDE.md - Complete reference (use Ctrl+F to search)"
echo "4. AWS_DEPLOYMENT_VISUAL.md - Diagrams and visuals"
echo "5. AWS_DEPLOYMENT_INDEX.md - Navigation guide"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Questions? Bugs? Need help?"
echo ""
echo "1. Search AWS_DEPLOYMENT_GUIDE.md for your issue"
echo "2. Check CloudWatch logs in AWS Console"
echo "3. Review the troubleshooting section"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "You've got this! 🚀"
echo ""
echo "═════════════════════════════════════════════════════════════════════"
