/**
 * Localization (i18n) System
 * Supports English and Swahili translations
 */

export const translations = {
  en: {
    // Common
    common: {
      search: 'Search',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      back: 'Back',
      close: 'Close',
      export: 'Export',
      import: 'Import',
      download: 'Download',
      upload: 'Upload',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Information',
      yes: 'Yes',
      no: 'No',
      confirm: 'Confirm',
      language: 'Language',
      currency: 'Currency',
      settings: 'Settings',
      help: 'Help',
      about: 'About',
      logout: 'Logout',
      profile: 'Profile',
    },

    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome',
      totalSales: 'Total Sales',
      todayRevenue: 'Today Revenue',
      pending: 'Pending Orders',
      completed: 'Completed Orders',
    },

    // Inventory
    inventory: {
      title: 'Inventory Management',
      description: 'Track inventory and stock levels',
      sku: 'SKU',
      productName: 'Product Name',
      stock: 'Stock',
      reorderLevel: 'Reorder Level',
      price: 'Price',
      category: 'Category',
      status: 'Status',
      actions: 'Actions',
      addProduct: 'Add Product',
      editProduct: 'Edit Product',
      deleteProduct: 'Delete Product',
      lowStock: 'Low Stock Alert',
      outOfStock: 'Out of Stock',
      inStock: 'In Stock',
      searchPlaceholder: 'Search by SKU, name, or category...',
      noResults: 'No products found',
      bulkUpdate: 'Bulk Update',
      printBarcode: 'Print Barcode',
      viewHistory: 'View History',
    },

    // Discounts
    discounts: {
      title: 'Discounts & Coupons',
      description: 'Manage promotion codes and discounts',
      code: 'Code',
      discountType: 'Discount Type',
      discountValue: 'Discount Value',
      percentage: 'Percentage',
      fixed: 'Fixed Amount',
      minPurchase: 'Minimum Purchase',
      maxUses: 'Maximum Uses',
      usedCount: 'Used Count',
      expiryDate: 'Expiry Date',
      status: 'Status',
      active: 'Active',
      expired: 'Expired',
      inactive: 'Inactive',
      addDiscount: 'Add Discount',
      editDiscount: 'Edit Discount',
      deleteDiscount: 'Delete Discount',
      searchPlaceholder: 'Search by code or description...',
      noResults: 'No discounts found',
      approveDiscount: 'Approve',
      rejectDiscount: 'Reject',
    },

    // Campaigns
    campaigns: {
      title: 'Email Campaigns',
      description: 'Manage marketing campaigns',
      campaignName: 'Campaign Name',
      subject: 'Subject',
      recipients: 'Recipients',
      sentCount: 'Sent Count',
      openRate: 'Open Rate',
      clickRate: 'Click Rate',
      status: 'Status',
      draft: 'Draft',
      scheduled: 'Scheduled',
      sent: 'Sent',
      failed: 'Failed',
      addCampaign: 'Add Campaign',
      editCampaign: 'Edit Campaign',
      deleteCampaign: 'Delete Campaign',
      sendNow: 'Send Now',
      schedule: 'Schedule',
      viewAnalytics: 'View Analytics',
      searchPlaceholder: 'Search by campaign name or subject...',
      noResults: 'No campaigns found',
      template: 'Template',
      preview: 'Preview',
    },

    // Shipping
    shipping: {
      title: 'Shipping & Delivery',
      description: 'Track shipments and manage deliveries',
      trackingNumber: 'Tracking Number',
      orderId: 'Order ID',
      carrier: 'Carrier',
      status: 'Status',
      estimatedDelivery: 'Estimated Delivery',
      shippedDate: 'Shipped Date',
      track: 'Track',
      pending: 'Pending',
      processing: 'Processing',
      inTransit: 'In Transit',
      outForDelivery: 'Out for Delivery',
      delivered: 'Delivered',
      failed: 'Failed',
      delayed: 'Delayed',
      searchPlaceholder: 'Search by tracking number or order ID...',
      noResults: 'No shipments found',
      viewDetails: 'View Details',
      reschedule: 'Reschedule',
      reportIssue: 'Report Issue',
    },

    // Invoices
    invoices: {
      title: 'Invoices',
      description: 'Generate and manage invoices',
      invoiceNumber: 'Invoice Number',
      orderNumber: 'Order Number',
      customer: 'Customer',
      amount: 'Amount',
      status: 'Status',
      date: 'Date',
      dueDate: 'Due Date',
      draft: 'Draft',
      sent: 'Sent',
      paid: 'Paid',
      overdue: 'Overdue',
      cancelled: 'Cancelled',
      generateInvoice: 'Generate Invoice',
      editInvoice: 'Edit Invoice',
      deleteInvoice: 'Delete Invoice',
      downloadPDF: 'Download PDF',
      sendEmail: 'Send Email',
      markAsPaid: 'Mark as Paid',
      searchPlaceholder: 'Search by invoice number or customer...',
      noResults: 'No invoices found',
      viewDetails: 'View Details',
    },

    // Payments
    payments: {
      title: 'Payment Processing',
      description: 'Manage payments and transactions',
      transactions: 'Transactions',
      transactionId: 'Transaction ID',
      reference: 'Reference',
      paymentMethods: 'Payment Methods',
      paymentGateway: 'Payment Gateway',
      mPesa: 'M-Pesa',
      haloPesa: 'HaloPesa',
      airtelMoney: 'Airtel Money',
      yas: 'Yas',
      nmbBank: 'NMB Bank',
      crdbBank: 'CRDB Bank',
      nbcBank: 'NBC Bank',
      stripe: 'Stripe',
      paypal: 'PayPal',
      totalTransactions: 'Total Transactions',
      successfulPayments: 'Successful Payments',
      pendingPayments: 'Pending Payments',
      recentTransactions: 'Recent Transactions',
      amount: 'Amount',
      method: 'Method',
      customer: 'Customer',
      status: 'Status',
      date: 'Date',
      completed: 'Completed',
      pending: 'Pending',
      failed: 'Failed',
      subscriptions: 'Subscriptions',
      reconciliation: 'Reconciliation',
      reconcile: 'Reconcile',
      revenue: 'Revenue',
      configure: 'Configure',
      manage: 'Manage',
      free: 'Free',
      refund: 'Refund',
    },

    // Reviews
    reviews: {
      title: 'Reviews & Ratings',
      description: 'Moderate and manage customer reviews',
      productName: 'Product Name',
      author: 'Author',
      rating: 'Rating',
      comment: 'Comment',
      date: 'Date',
      status: 'Status',
      approved: 'Approved',
      pending: 'Pending',
      rejected: 'Rejected',
      approveReview: 'Approve',
      rejectReview: 'Reject',
      deleteReview: 'Delete',
      searchPlaceholder: 'Search by product or author name...',
      noResults: 'No reviews found',
      viewDetails: 'View Details',
      helpful: 'Helpful',
      notHelpful: 'Not Helpful',
    },

    // Messages
    messages: {
      title: 'Messages & Support',
      description: 'Manage customer support tickets',
      ticketId: 'Ticket ID',
      subject: 'Subject',
      customer: 'Customer',
      priority: 'Priority',
      status: 'Status',
      createdDate: 'Created Date',
      open: 'Open',
      resolved: 'Resolved',
      closed: 'Closed',
      urgent: 'Urgent',
      high: 'High',
      normal: 'Normal',
      low: 'Low',
      reply: 'Reply',
      resolve: 'Resolve',
      closeTicket: 'Close Ticket',
      reopen: 'Reopen',
      searchPlaceholder: 'Search by ticket ID or subject...',
      noResults: 'No messages found',
      viewDetails: 'View Details',
      attachFile: 'Attach File',
    },

    // Reports
    reports: {
      title: 'Reports & Analytics',
      description: 'Sales reports and customer analytics',
      salesReport: 'Sales Report',
      customerReport: 'Customer Report',
      productPerformance: 'Product Performance',
      revenueTrend: 'Revenue Trend',
      topProducts: 'Top Products',
      topCustomers: 'Top Customers',
      exportReport: 'Export Report',
      dateRange: 'Date Range',
      from: 'From',
      to: 'To',
      generate: 'Generate Report',
      searchPlaceholder: 'Search reports...',
      noResults: 'No reports found',
      viewDetails: 'View Details',
      downloadPDF: 'Download PDF',
    },

    // Settings
    settings: {
      title: 'Mipangilio',
      general: 'Mipangilio ya Jumla',
      security: 'Usalama',
      notifications: 'Arifa',
      language: 'Lugha',
      currencies: 'Sarafu',
    },

    // Analytics
    analytics: {
      title: 'Dashibodi ya Uchambuzi',
      description: 'Fuatilia mauzo, wateja, na viashiria vya utendaji',
      totalSales: 'Jumla ya Mauzo',
      totalRevenue: 'Jumla ya Mapato',
      totalOrders: 'Jumla ya Maamar',
      totalCustomers: 'Jumla ya Wateja',
      averageOrderValue: 'Wastani wa Thamani ya Amri',
      conversionRate: 'Kiwango cha Ubadilishaji',
      salesTrend: 'Mwelekeo wa Mauzo',
      topProducts: 'Bidhaa Bora',
      customerGrowth: 'Ukuaji wa Wateja',
      revenueByMonth: 'Mapato kwa Mwezi',
      ordersByStatus: 'Maamar kwa Hali',
      exportReport: 'Hamisha Ripoti',
      viewDetails: 'Tazama Maelezo',
    },

    // CRM
    crm: {
      title: 'Usimamizi wa Mahusiano ya Wateja',
      description: 'Dhibiti wateja, sehemu, na programu za zawadi',
      customers: 'Wateja',
      segments: 'Sehemu za Wateja',
      loyaltyProgram: 'Programu ya Uaminifu',
      customerProfile: 'Wasifu wa Mteja',
      purchaseHistory: 'Historia ya Ununuzi',
      vipCustomers: 'Wateja VIP',
      regularCustomers: 'Wateja Kawaida',
      newCustomers: 'Wateja Wapya',
      totalSpent: 'Jumla ya Expenditure',
      lastPurchase: 'Ununuzi wa Mwisho',
      points: 'Pointi za Uaminifu',
      rewardsTier: 'Kiwango cha Zawadi',
      segmentCustomers: 'Sehemu Wateja',
    },

    // RBAC
    rbac: {
      title: 'Udhibiti wa Ufikiliaji',
      description: 'Dhibiti majukumu ya watumiaji na ruhusa',
      roles: 'Majukumu',
      permissions: 'Ruhusa',
      admin: 'Msimamizi',
      manager: 'Meneja',
      staff: 'Wafanyakazi',
      viewer: 'Mwangalizi',
      users: 'Watumiaji',
      assignRole: 'Pewa Jukumu',
      activityLog: 'Logi ya Shughuli',
      auditTrail: 'Ufuataji wa Ukaguzi',
      lastLogin: 'Kuingia mwisho',
      accessLevel: 'Kiwango cha Ufikiliaji',
      addUser: 'Ongeza Mtumiaji',
      removeUser: 'Ondoa Mtumiaji',
    },

    // Workflows
    workflows: {
      title: 'Otomesheni & Mabadiliko ya Kazi',
      description: 'Tengeneza mabadiliko otomatiki ya kazi na kanuni',
      workflows: 'Mabadiliko ya Kazi',
      rules: 'Kanuni',
      triggers: 'Kichochezi',
      actions: 'Vitendo',
      createWorkflow: 'Tengeneza Badiliko la Kazi',
      editWorkflow: 'Hariri Badiliko la Kazi',
      activeWorkflows: 'Mabadiliko ya Kazi Yanayofanya Kazi',
      executionLog: 'Logi ya Utekelezaji',
      autoInvoice: 'Wasifu Otomatiki',
      autoNotify: 'Arifa Otomatiki',
      autoUpdateInventory: 'Sasisha Hesabu Otomatiki',
      scheduled: 'Imepangwa',
      executed: 'Zimefanywa',
      failed: 'Zimeshindwa',
    },

    // Forecasting
    forecasting: {
      title: 'Utabiri wa Hesabu',
      description: 'Utabiri wa mahitaji unaosupported na AI na mapendekezo',
      demandForecast: 'Utabiri wa Mahitaji',
      predictedDemand: 'Mahitaji Yaliyotabirwa',
      stockRecommendation: 'Mapendekezo ya Hisa',
      forecastAccuracy: 'Usahihi wa Utabiri',
      reorderPoint: 'Mahali pa Kuagiza Upya',
      safetyStock: 'Hisa ya Usalama',
      leadTime: 'Wakati wa Kubadilika',
      nextRestockDate: 'Tarehe ya Kurekebisha Ifuatayo',
      warehouse: 'Ghala',
      location: 'Mahali',
      expirationDate: 'Tarehe ya Kumalizika',
      autoReorder: 'Kuagiza Upya Otomatiki',
    },

    // Payments
    payments: {
      title: 'Usindikaji wa Malipo',
      description: 'Dhibiti malipo na miamala',
      transactions: 'Miamala',
      paymentGateway: 'Njia ya Malipo',
      mPesa: 'M-Pesa',
      haloPesa: 'HaloPesa',
      airtelMoney: 'Airtel Money',
      yas: 'Yas',
      nmbBank: 'NMB Bank',
      crdbBank: 'CRDB Bank',
      nbcBank: 'NBC Bank',
      stripe: 'Stripe',
      paypal: 'PayPal',
      subscription: 'Jioni',
      recurring: 'Inayorudia',
      oneTime: 'Mara Moja',
      reconciliation: 'Urekebishaji',
      paymentStatus: 'Hali ya Malipo',
      completed: 'Imekamilika',
      pending: 'Inasubiri',
      failed: 'Imeshindwa',
      refund: 'Kurejesha Fedha',
      amount: 'Kiasi',
    },

    // Shipping
    shipping: {
      title: 'Utoaji wa Juu',
      description: 'Dhibiti wabebaji na uongezaji wa mizigo',
      carriers: 'Wabebaji',
      fedex: 'FedEx',
      ups: 'UPS',
      dhl: 'DHL',
      shippingCost: 'Gharama ya Utoaji',
      estimatedDelivery: 'Utoaji Unatarajiwa',
      trackingNumber: 'Namba ya Ufuataji',
      returns: 'Kurudisha',
      rma: 'Ruhusa ya Kurudisha Bidhaa',
      proofOfDelivery: 'Uthibitisho wa Utoaji',
      compareRates: 'Linganisha Bei',
      selectCarrier: 'Chagua Mbebaji',
    },

    // Business Intelligence
    bi: {
      title: 'Akili ya Biashara',
      description: 'Ripoti za juu na maarifa',
      customReport: 'Ripoti Customized',
      scheduleReport: 'Ripoti ya Ratiba',
      exportData: 'Hamisha Data',
      dataVisualization: 'Uigaji wa Data',
      heatmap: 'Ramani ya Joto',
      timeline: 'Mstari wa Muda',
      comparison: 'Kulinganisha',
      prediction: 'Utabiri',
      email: 'Barua Pepe',
      frequency: 'Mzunguko',
      daily: 'Kila Siku',
      weekly: 'Kila Juma',
      monthly: 'Kila Mwezi',
    },

    // Multi-Channel
    multichannel: {
      title: 'Ujumuishaji wa Chaneli Nyingi',
      description: 'Kuunganisha kwenye chaneli nyingi za mauzo',
      channels: 'Chaneli za Mauzo',
      shopify: 'Shopify',
      woocommerce: 'WooCommerce',
      amazon: 'Amazon',
      connected: 'Imeunganishwa',
      notConnected: 'Haijaunganiswi',
      syncInventory: 'Synchronize Hesabu',
      syncOrders: 'Synchronize Maamar',
      syncCustomers: 'Synchronize Wateja',
      connectionStatus: 'Hali ya Unganisho',
      lastSync: 'Synchronize ya Mwisho',
    },

    // Mobile
    mobile: {
      title: 'Programu ya Simu',
      description: 'Dhibiti biashara njiani',
      downloadApp: 'Download Programu',
      ios: 'Programu ya iOS',
      android: 'Programu ya Android',
      features: 'Sifa',
      offlineMode: 'Mtindo wa Offline',
      qrScanning: 'Ufuataji wa QR Code',
      pushNotifications: 'Arifa za Push',
      general: 'General Settings',
      security: 'Security',
      notifications: 'Notifications',
      language: 'Language',
      currencies: 'Currencies',
    },

    // Analytics
    analytics: {
      title: 'Analytics Dashboard',
      description: 'Track sales, customers, and performance metrics',
      totalSales: 'Total Sales',
      totalRevenue: 'Total Revenue',
      totalOrders: 'Total Orders',
      totalCustomers: 'Total Customers',
      averageOrderValue: 'Average Order Value',
      conversionRate: 'Conversion Rate',
      salesTrend: 'Sales Trend',
      topProducts: 'Top Products',
      customerGrowth: 'Customer Growth',
      revenueByMonth: 'Revenue by Month',
      ordersByStatus: 'Orders by Status',
      exportReport: 'Export Report',
      viewDetails: 'View Details',
    },

    // CRM
    crm: {
      title: 'Customer Relationship Management',
      description: 'Manage customers, segments, and loyalty programs',
      customers: 'Customers',
      segments: 'Customer Segments',
      loyaltyProgram: 'Loyalty Program',
      customerProfile: 'Customer Profile',
      purchaseHistory: 'Purchase History',
      vipCustomers: 'VIP Customers',
      regularCustomers: 'Regular Customers',
      newCustomers: 'New Customers',
      totalSpent: 'Total Spent',
      lastPurchase: 'Last Purchase',
      points: 'Loyalty Points',
      rewardsTier: 'Rewards Tier',
      segmentCustomers: 'Segment Customers',
    },

    // RBAC
    rbac: {
      title: 'Access Control',
      description: 'Manage user roles and permissions',
      roles: 'Roles',
      permissions: 'Permissions',
      admin: 'Administrator',
      manager: 'Manager',
      staff: 'Staff',
      viewer: 'Viewer',
      users: 'Users',
      assignRole: 'Assign Role',
      activityLog: 'Activity Log',
      auditTrail: 'Audit Trail',
      lastLogin: 'Last Login',
      accessLevel: 'Access Level',
      addUser: 'Add User',
      removeUser: 'Remove User',
    },

    // Workflows
    workflows: {
      title: 'Automation & Workflows',
      description: 'Create automated workflows and rules',
      workflows: 'Workflows',
      rules: 'Rules',
      triggers: 'Triggers',
      actions: 'Actions',
      createWorkflow: 'Create Workflow',
      editWorkflow: 'Edit Workflow',
      activeWorkflows: 'Active Workflows',
      executionLog: 'Execution Log',
      autoInvoice: 'Auto-generate Invoice',
      autoNotify: 'Auto-send Notification',
      autoUpdateInventory: 'Auto-update Inventory',
      scheduled: 'Scheduled',
      executed: 'Executed',
      failed: 'Failed',
    },

    // Forecasting
    forecasting: {
      title: 'Inventory Forecasting',
      description: 'AI-powered demand forecasting and recommendations',
      demandForecast: 'Demand Forecast',
      predictedDemand: 'Predicted Demand',
      stockRecommendation: 'Stock Recommendation',
      forecastAccuracy: 'Forecast Accuracy',
      reorderPoint: 'Reorder Point',
      safetyStock: 'Safety Stock',
      leadTime: 'Lead Time',
      nextRestockDate: 'Next Restock Date',
      warehouse: 'Warehouse',
      location: 'Location',
      expirationDate: 'Expiration Date',
      autoReorder: 'Auto-Reorder',
    },

    // Payments
    payments: {
      title: 'Payment Processing',
      description: 'Manage payments and transactions',
      transactions: 'Transactions',
      paymentGateway: 'Payment Gateway',
      mPesa: 'M-Pesa',
      stripe: 'Stripe',
      paypal: 'PayPal',
      subscription: 'Subscription',
      recurring: 'Recurring',
      oneTime: 'One Time',
      reconciliation: 'Reconciliation',
      paymentStatus: 'Payment Status',
      completed: 'Completed',
      pending: 'Pending',
      failed: 'Failed',
      refund: 'Refund',
      amount: 'Amount',
    },

    // Shipping
    shipping: {
      title: 'Advanced Shipping',
      description: 'Manage carriers and logistics',
      carriers: 'Carriers',
      fedex: 'FedEx',
      ups: 'UPS',
      dhl: 'DHL',
      shippingCost: 'Shipping Cost',
      estimatedDelivery: 'Estimated Delivery',
      trackingNumber: 'Tracking Number',
      returns: 'Returns',
      rma: 'Return Merchandise Authorization',
      proofOfDelivery: 'Proof of Delivery',
      compareRates: 'Compare Rates',
      selectCarrier: 'Select Carrier',
    },

    // Business Intelligence
    bi: {
      title: 'Business Intelligence',
      description: 'Advanced reporting and insights',
      customReport: 'Custom Report',
      scheduleReport: 'Schedule Report',
      exportData: 'Export Data',
      dataVisualization: 'Data Visualization',
      heatmap: 'Heatmap',
      timeline: 'Timeline',
      comparison: 'Comparison',
      prediction: 'Prediction',
      email: 'Email',
      frequency: 'Frequency',
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
    },

    // Multi-Channel
    multichannel: {
      title: 'Multi-Channel Integration',
      description: 'Connect to multiple sales channels',
      channels: 'Sales Channels',
      shopify: 'Shopify',
      woocommerce: 'WooCommerce',
      amazon: 'Amazon',
      connected: 'Connected',
      notConnected: 'Not Connected',
      syncInventory: 'Sync Inventory',
      syncOrders: 'Sync Orders',
      syncCustomers: 'Sync Customers',
      connectionStatus: 'Connection Status',
      lastSync: 'Last Sync',
    },

    // Mobile
    mobile: {
      title: 'Mobile App',
      description: 'Manage business on the go',
      downloadApp: 'Download App',
      ios: 'iOS App',
      android: 'Android App',
      features: 'Features',
      offlineMode: 'Offline Mode',
      qrScanning: 'QR Code Scanning',
      pushNotifications: 'Push Notifications',
      description: 'Configure store settings',
      general: 'General Settings',
      storeName: 'Store Name',
      storeDescription: 'Store Description',
      storeEmail: 'Store Email',
      storePhone: 'Store Phone',
      storeAddress: 'Store Address',
      languages: 'Languages',
      selectLanguage: 'Select Language',
      english: 'English',
      swahili: 'Swahili',
      currencies: 'Currencies',
      selectCurrency: 'Select Currency',
      usd: 'USD (US Dollar)',
      tzs: 'TZS (Tanzanian Shilling)',
      eur: 'EUR (Euro)',
      notifications: 'Notifications',
      emailNotifications: 'Email Notifications',
      smsNotifications: 'SMS Notifications',
      pushNotifications: 'Push Notifications',
      security: 'Security',
      twoFactorAuth: '2FA Authentication',
      changePassword: 'Change Password',
      apiKeys: 'API Keys',
      theme: 'Theme',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      timeZone: 'Time Zone',
      dateFormat: 'Date Format',
      timeFormat: 'Time Format',
      businessHours: 'Business Hours',
      taxRate: 'Tax Rate',
      shippingSettings: 'Shipping Settings',
      paymentMethods: 'Payment Methods',
      backup: 'Backup',
      createBackup: 'Create Backup',
      restoreBackup: 'Restore Backup',
      about: 'About',
      version: 'Version',
      saveSettings: 'Save Settings',
      settingsSaved: 'Settings saved successfully',
      settingsFailed: 'Failed to save settings',
    },

    // Sidebar
    sidebar: {
      dashboard: 'Dashboard',
      inventory: 'Inventory',
      discounts: 'Discounts',
      campaigns: 'Campaigns',
      shipping: 'Shipping',
      invoices: 'Invoices',
      reviews: 'Reviews',
      messages: 'Messages',
      reports: 'Reports',
      settings: 'Settings',
      logout: 'Logout',
    },

    // Live Chat
    liveChat: {
      title: 'Live Chat Support',
      online: 'Online',
      offline: 'Offline',
      conversations: 'Conversations',
      newChat: 'New Chat',
      customerName: 'Customer Name',
      customerEmail: 'Customer Email',
      startChat: 'Start Chat',
      noConversations: 'No active conversations',
      selectChat: 'Select a conversation',
      selectChatDesc: 'Choose a conversation from the list to start chatting',
      typeMessage: 'Type a message...',
      send: 'Send',
      closeChat: 'Close Chat',
      noMessages: 'Start the conversation',
      noMessagesYet: 'Start the conversation',
    },

    // Notifications
    notifications: {
      title: 'Notifications',
      unread: 'Unread',
      filter: 'Filter',
      markAllRead: 'Mark All Read',
      allNotifications: 'All Notifications',
      orders: 'Orders',
      payments: 'Payments',
      messages: 'Messages',
      reviews: 'Reviews',
      customers: 'Customers',
      inventory: 'Inventory',
      noNotifications: 'No notifications',
      markAsRead: 'Mark as read',
      delete: 'Delete',
      orderNotification: 'Order Update',
      paymentNotification: 'Payment Received',
      messageNotification: 'New Message',
      reviewNotification: 'New Review',
      customerNotification: 'Customer Update',
      inventoryNotification: 'Stock Alert',
    },

    // Reviews
    reviews: {
      title: 'Customer Reviews',
      reviews: 'Reviews',
      totalReviews: 'Total Reviews',
      verifiedPurchases: 'Verified Purchases',
      withImages: 'With Images',
      sortBy: 'Sort By',
      mostRecent: 'Most Recent',
      mostHelpful: 'Most Helpful',
      highestRating: 'Highest Rating',
      lowestRating: 'Lowest Rating',
      filterByRating: 'Filter By Rating',
      allRatings: 'All Ratings',
      stars: 'Stars',
      star: 'Star',
      noReviews: 'No reviews yet',
      verifiedPurchase: 'Verified Purchase',
      verified: 'Verified',
      helpful: 'Helpful',
      verify: 'Verify',
      delete: 'Delete',
    },

    // Search Analytics
    searchAnalytics: {
      title: 'Search Analytics',
      subtitle: 'Track popular searches and customer behavior',
      timeframe: 'Timeframe',
      totalSearches: 'Total Searches',
      uniqueSearches: 'Unique Searches',
      avgPerDay: 'Avg Per Day',
      topSearch: 'Top Search',
      populartSearches: 'Popular Searches',
      noData: 'No search data available',
      searches: 'Searches',
      clicks: 'Clicks',
      ctr: 'CTR',
      clear: 'Clear',
      insights: 'Insights & Recommendations',
      topSearchTrend: 'Top Search Trend',
      customerBehavior: 'Customer Behavior',
      optimization: 'SEO Optimization',
      general: 'General',
    },

    // Calendar
    calendar: {
      title: 'Business Calendar',
      description: 'Manage events, schedules, and appointments',
      previous: 'Previous',
      next: 'Next',
      today: 'Today',
      monthView: 'Month',
      weekView: 'Week',
      dayView: 'Day',
      addEvent: 'Add Event',
      editEvent: 'Edit Event',
      eventTitle: 'Event Title',
      enterTitle: 'Enter event title',
      eventType: 'Event Type',
      typeDelivery: 'Delivery',
      typePayment: 'Payment',
      typeInventory: 'Inventory Check',
      typeMeeting: 'Meeting',
      typeStock: 'Stock Arrival',
      time: 'Time',
      customer: 'Customer',
      enterCustomer: 'Enter customer name',
      orderId: 'Order ID',
      amount: 'Amount',
      location: 'Location',
      enterLocation: 'Enter location',
      quantity: 'Quantity',
      totalEvents: 'Total Events',
      save: 'Save Event',
      update: 'Update Event',
      delete: 'Delete Event',
      cancel: 'Cancel',
    },
  },

  sw: {
    // Common
    common: {
      search: 'Tafuta',
      save: 'Hifadhi',
      cancel: 'Ghairi',
      delete: 'Futa',
      edit: 'Hariri',
      add: 'Ongeza',
      back: 'Rudi',
      close: 'Funga',
      export: 'Hamisha',
      import: 'Ingiza',
      download: 'Pakua',
      upload: 'Pakia',
      loading: 'Inapakia...',
      error: 'Kosa',
      success: 'Kama inavyotaka',
      warning: 'Onyo',
      info: 'Taarifa',
      yes: 'Ndiyo',
      no: 'Hapana',
      confirm: 'Thibitisha',
      language: 'Lugha',
      currency: 'Sarafu',
      settings: 'Mipangilio',
      help: 'Msaada',
      about: 'Kuhusu',
      logout: 'Toka',
      profile: 'Wasifu',
    },

    // Dashboard
    dashboard: {
      title: 'Dashibodi',
      welcome: 'Karibu',
      totalSales: 'Jumla ya Mauzo',
      todayRevenue: 'Mapato ya Leo',
      pending: 'Miamala Inayosubiri',
      completed: 'Miamala Imekamilika',
    },

    // Inventory
    inventory: {
      title: 'Usimamizi wa Hesabu',
      description: 'Fuatilia hesabu na ngazi za hisa',
      sku: 'SKU',
      productName: 'Jina la Bidhaa',
      stock: 'Hesabu',
      reorderLevel: 'Kiwango cha Kuagiza Tena',
      price: 'Bei',
      category: 'Jamii',
      status: 'Hali',
      actions: 'Vitendo',
      addProduct: 'Ongeza Bidhaa',
      editProduct: 'Hariri Bidhaa',
      deleteProduct: 'Futa Bidhaa',
      lowStock: 'Onyo wa Hesabu Nyingi',
      outOfStock: 'Haipo Katika Hesabu',
      inStock: 'Katika Hesabu',
      searchPlaceholder: 'Tafuta kwa SKU, jina au jamii...',
      noResults: 'Bidhaa hazikupatikana',
      bulkUpdate: 'Sasisho la Wingi',
      printBarcode: 'Chapisha Barcode',
      viewHistory: 'Angalia Historia',
    },

    // Discounts
    discounts: {
      title: 'Punguzo na Tikiti',
      description: 'Simamia msimbo wa mkutano na punguzo',
      code: 'Msimbo',
      discountType: 'Aina ya Punguzo',
      discountValue: 'Kiwango cha Punguzo',
      percentage: 'Asilimia',
      fixed: 'Kiwango Kilichowekwa',
      minPurchase: 'Ununuzi wa Chini Kabisa',
      maxUses: 'Matumizi ya Juu Zaidi',
      usedCount: 'Hesabu ya Matumizi',
      expiryDate: 'Tarehe ya Kumalizia',
      status: 'Hali',
      active: 'Faida',
      expired: 'Umekalizia',
      inactive: 'Haipo',
      addDiscount: 'Ongeza Punguzo',
      editDiscount: 'Hariri Punguzo',
      deleteDiscount: 'Futa Punguzo',
      searchPlaceholder: 'Tafuta kwa msimbo au maelezo...',
      noResults: 'Punguzo hazikupatikana',
      approveDiscount: 'Kubali',
      rejectDiscount: 'Kataa',
    },

    // Campaigns
    campaigns: {
      title: 'Kampeni za Barua',
      description: 'Simamia kampeni za uendeshaji',
      campaignName: 'Jina la Kampeni',
      subject: 'Mada',
      recipients: 'Wapokeaji',
      sentCount: 'Hesabu ya Kutumwa',
      openRate: 'Kiwango cha Kufungua',
      clickRate: 'Kiwango cha Kubonyeza',
      status: 'Hali',
      draft: 'Rasimu',
      scheduled: 'Iliyopangwa',
      sent: 'Imetumwa',
      failed: 'Imeshindwa',
      addCampaign: 'Ongeza Kampeni',
      editCampaign: 'Hariri Kampeni',
      deleteCampaign: 'Futa Kampeni',
      sendNow: 'Tuma Sasa',
      schedule: 'Panga',
      viewAnalytics: 'Angalia Uchambuzi',
      searchPlaceholder: 'Tafuta kwa jina au mada...',
      noResults: 'Kampeni hazikupatikana',
      template: 'Kielelezo',
      preview: 'Muhtasari',
    },

    // Shipping
    shipping: {
      title: 'Utoaji na Utoaji',
      description: 'Fuatilia minoano na kuongeza utoaji',
      trackingNumber: 'Namba ya Ufuatiliaji',
      orderId: 'Namba ya Agizo',
      carrier: 'Mchezaji',
      status: 'Hali',
      estimatedDelivery: 'Utoaji Unatarajiwa',
      shippedDate: 'Tarehe ya Kutumwa',
      track: 'Fuatilia',
      pending: 'Inayosubiri',
      processing: 'Inahadiithwa',
      inTransit: 'Njiani',
      outForDelivery: 'Njiani kwa Utoaji',
      delivered: 'Umefika',
      failed: 'Imeshindwa',
      delayed: 'Imechelewa',
      searchPlaceholder: 'Tafuta kwa namba ya ufuatiliaji au agizo...',
      noResults: 'Minoano haijupatikana',
      viewDetails: 'Angalia Maelezo',
      reschedule: 'Ratiba Tena',
      reportIssue: 'Ripoti Tatizo',
    },

    // Invoices
    invoices: {
      title: 'Ankara',
      description: 'Tengeneza na simamia ankara',
      invoiceNumber: 'Namba ya Ankara',
      orderNumber: 'Namba ya Agizo',
      customer: 'Mteja',
      amount: 'Kiwango',
      status: 'Hali',
      date: 'Tarehe',
      dueDate: 'Tarehe ya Kuoza',
      draft: 'Rasimu',
      sent: 'Imetumwa',
      paid: 'Hulipwa',
      overdue: 'Imepita',
      cancelled: 'Imefutwa',
      generateInvoice: 'Tengeneza Ankara',
      editInvoice: 'Hariri Ankara',
      deleteInvoice: 'Futa Ankara',
      downloadPDF: 'Pakua PDF',
      sendEmail: 'Tuma Barua',
      markAsPaid: 'Alama kama Kulipwa',
      searchPlaceholder: 'Tafuta kwa ankara au mteja...',
      noResults: 'Ankara hazikupatikana',
      viewDetails: 'Angalia Maelezo',
    },

    // Reviews
    reviews: {
      title: 'Mapitio na Miamio',
      description: 'Fanyia kazi na simamia mapitio ya mteja',
      productName: 'Jina la Bidhaa',
      author: 'Mwandishi',
      rating: 'Miamio',
      comment: 'Kauli',
      date: 'Tarehe',
      status: 'Hali',
      approved: 'Kwa Sababu',
      pending: 'Inayosubiri',
      rejected: 'Iliyokataliwa',
      approveReview: 'Kubali',
      rejectReview: 'Kataa',
      deleteReview: 'Futa',
      searchPlaceholder: 'Tafuta kwa bidhaa au jina...',
      noResults: 'Mapitio hayakupatikana',
      viewDetails: 'Angalia Maelezo',
      helpful: 'Msaada',
      notHelpful: 'Sio Msaada',
    },

    // Messages
    messages: {
      title: 'Ujumbe na Msaada',
      description: 'Simamia tikiti za msaada wa mteja',
      ticketId: 'Namba ya Tikiti',
      subject: 'Mada',
      customer: 'Mteja',
      priority: 'Umuhimu',
      status: 'Hali',
      createdDate: 'Tarehe ya Kutengeneza',
      open: 'Funguka',
      resolved: 'Kutatuliwa',
      closed: 'Funga',
      urgent: 'Haraka',
      high: 'Juu',
      normal: 'Kawaida',
      low: 'Chini',
      reply: 'Jibu',
      resolve: 'Tatua',
      closeTicket: 'Funga Tikiti',
      reopen: 'Fungua Tena',
      searchPlaceholder: 'Tafuta kwa tikiti au mada...',
      noResults: 'Ujumbe haujupatikana',
      viewDetails: 'Angalia Maelezo',
      attachFile: 'Ambatanisha Faili',
    },

    // Reports
    reports: {
      title: 'Ripoti na Uchambuzi',
      description: 'Ripoti za mauzo na uchambuzi wa mteja',
      salesReport: 'Ripoti ya Mauzo',
      customerReport: 'Ripoti ya Mteja',
      productPerformance: 'Utendaji wa Bidhaa',
      revenueTrend: 'Mwelekeo wa Mapato',
      topProducts: 'Bidhaa za Juu',
      topCustomers: 'Wateja wa Juu',
      exportReport: 'Hamisha Ripoti',
      dateRange: 'Masafa ya Tarehe',
      from: 'Kutoka',
      to: 'Kwa',
      generate: 'Tengeneza Ripoti',
      searchPlaceholder: 'Tafuta ripoti...',
      noResults: 'Ripoti hazikupatikana',
      viewDetails: 'Angalia Maelezo',
      downloadPDF: 'Pakua PDF',
    },

    // Settings
    settings: {
      title: 'Mipangilio',
      description: 'Sanidi mipangilio ya duka',
      general: 'Mipangilio ya Jumla',
      storeName: 'Jina la Duka',
      storeDescription: 'Maelezo ya Duka',
      storeEmail: 'Barua ya Duka',
      storePhone: 'Simu ya Duka',
      storeAddress: 'Anwani ya Duka',
      languages: 'Lugha',
      selectLanguage: 'Chagua Lugha',
      english: 'Kiingereza',
      swahili: 'Kiswahili',
      currencies: 'Sarafu',
      selectCurrency: 'Chagua Sarafu',
      usd: 'USD (Dola ya Amerika)',
      tzs: 'TZS (Shilingi la Tanzaniya)',
      eur: 'EUR (Euro)',
      notifications: 'Arifa',
      emailNotifications: 'Arifa za Barua',
      smsNotifications: 'Arifa za SMS',
      pushNotifications: 'Arifa za Kubonyeza',
      security: 'Usalama',
      twoFactorAuth: 'Ufasiriaji wa 2FA',
      changePassword: 'Badili Nenosiri',
      apiKeys: 'Funguo za API',
      theme: 'Mandhari',
      darkMode: 'Mtindo Giza',
      lightMode: 'Mtindo Nyepesi',
      timeZone: 'Eneo la Wakati',
      dateFormat: 'Umbizo la Tarehe',
      timeFormat: 'Umbizo la Wakati',
      businessHours: 'Saa za Biashara',
      taxRate: 'Kiwango cha Kodi',
      shippingSettings: 'Mipangilio ya Utoaji',
      paymentMethods: 'Njia za Kulipa',
      backup: 'Hifadhi',
      createBackup: 'Tengeneza Hifadhi',
      restoreBackup: 'Rejesha Hifadhi',
      about: 'Kuhusu',
      version: 'Toleo',
      saveSettings: 'Hifadhi Mipangilio',
      settingsSaved: 'Mipangilio imehifadhiwa kwa ufanisi',
      settingsFailed: 'Imeshindwa kuhifadhi mipangilio',
    },

    // Sidebar
    sidebar: {
      dashboard: 'Dashibodi',
      inventory: 'Hesabu',
      discounts: 'Punguzo',
      campaigns: 'Kampeni',
      shipping: 'Utoaji',
      invoices: 'Ankara',
      reviews: 'Mapitio',
      messages: 'Ujumbe',
      reports: 'Ripoti',
      settings: 'Mipangilio',
      logout: 'Toka',
    },

    // Calendar
    calendar: {
      title: 'Kalenda',
      description: 'Simamia matukio, uendezaji, na miadi',
      previous: 'Iliyotangulia',
      next: 'Inayofuata',
      today: 'Leo',
      monthView: 'Mwezi',
      weekView: 'Juma',
      dayView: 'Siku',
      addEvent: 'Ongeza Matukio',
      editEvent: 'Hariri Matukio',
      eventTitle: 'Jina la Matukio',
      enterTitle: 'Ingiza jina la matukio',
      eventType: 'Aina ya Matukio',
      typeDelivery: 'Uendezaji',
      typePayment: 'Malipo',
      typeInventory: 'Ukaguzi wa Hifadhi',
      typeMeeting: 'Mikutano',
      typeStock: 'Kuwasili kwa Hisa',
      time: 'Wakati',
      customer: 'Mteja',
      enterCustomer: 'Ingiza jina la mteja',
      orderId: 'Nambari ya Amri',
      amount: 'Kiwango',
      location: 'Mahali',
      enterLocation: 'Ingiza mahali',
      quantity: 'Kiasi',
      totalEvents: 'Jumla ya Matukio',
      save: 'Hifadhi Matukio',
      update: 'Sasisha Matukio',
      delete: 'Futa Matukio',
      cancel: 'Ghairi',
    },

    // Live Chat (Swahili)
    liveChat: {
      title: 'Msaada wa Mazungumzo Halisi',
      online: 'Mtandaoni',
      offline: 'Nje ya Mtandao',
      conversations: 'Mazungumzo',
      newChat: 'Mazungumzo Mapya',
      customerName: 'Jina la Mteja',
      customerEmail: 'Barua ya Mteja',
      startChat: 'Anza Mazungumzo',
      noConversations: 'Hakuna mazungumzo yanayofanya kazi',
      selectChat: 'Chagua mazungumzo',
      selectChatDesc: 'Chagua mazungumzo kutoka kwa orodha ya kuanza kuzungumza',
      typeMessage: 'Andika ujumbe...',
      send: 'Tuma',
      closeChat: 'Funga Mazungumzo',
      noMessages: 'Anza mazungumzo',
      noMessagesYet: 'Anza mazungumzo',
    },

    // Notifications (Swahili)
    notifications: {
      title: 'Arifa',
      unread: 'Ambata Kusomeka',
      filter: 'Chuja',
      markAllRead: 'Weka Alama Yote Somi',
      allNotifications: 'Arifa Zote',
      orders: 'Maagizo',
      payments: 'Malipo',
      messages: 'Ujumbe',
      reviews: 'Ukaguzi',
      customers: 'Wateja',
      inventory: 'Hazina',
      noNotifications: 'Hakuna arifa',
      markAsRead: 'Weka Alama Kama Ilusomwa',
      delete: 'Futa',
      orderNotification: 'Sasisho la Amri',
      paymentNotification: 'Malipo Yaliyopokelewa',
      messageNotification: 'Ujumbe Mpya',
      reviewNotification: 'Ukaguzi Mpya',
      customerNotification: 'Sasisho la Mteja',
      inventoryNotification: 'Onyo la Stock',
    },

    // Reviews (Swahili)
    reviews: {
      title: 'Ukaguzi wa Mteja',
      reviews: 'Ukaguzi',
      totalReviews: 'Jumla ya Ukaguzi',
      verifiedPurchases: 'Ununuzi Uliothibitishwa',
      withImages: 'Pamoja na Picha',
      sortBy: 'Panga Kwa',
      mostRecent: 'Mpya Zaidi',
      mostHelpful: 'Msaada Zaidi',
      highestRating: 'Kiwango Cha Juu',
      lowestRating: 'Kiwango cha Chini',
      filterByRating: 'Chuja Kwa Kiwango',
      allRatings: 'Kiwango Kote',
      stars: 'Nyota',
      star: 'Nyota',
      noReviews: 'Hakuna ukaguzi bado',
      verifiedPurchase: 'Ununuzi Uliothibitishwa',
      verified: 'Imethibitishwa',
      helpful: 'Msaada',
      verify: 'Thibiti',
      delete: 'Futa',
    },

    // Search Analytics (Swahili)
    searchAnalytics: {
      title: 'Uchambuzi wa Utafutaji',
      subtitle: 'Fuatilia utafutaji maajabu na tabia za mteja',
      timeframe: 'Muda',
      totalSearches: 'Jumla ya Utafutaji',
      uniqueSearches: 'Utafutaji wa Nchi Tofauti',
      avgPerDay: 'Wastani kwa Siku',
      topSearch: 'Utafutaji wa Juu',
      populartSearches: 'Utafutaji Maajabu',
      noData: 'Hakuna data ya utafutaji',
      searches: 'Utafutaji',
      clicks: 'Kubofya',
      ctr: 'CTR',
      clear: 'Futa',
      insights: 'Imbukizo & Mapendekezo',
      topSearchTrend: 'Mwenendo wa Juu wa Utafutaji',
      customerBehavior: 'Tabia ya Mteja',
      optimization: 'Uboreshaji wa SEO',
      general: 'Jumla',
    },
  },
};

/**
 * Get translation for a key
 * @param {string} language - 'en' or 'sw'
 * @param {string} section - e.g., 'common', 'inventory', 'dashboard'
 * @param {string} key - the translation key
 * @returns {string} translated text or key if not found
 */
export const getTranslation = (language, section, key) => {
  try {
    const text = translations[language]?.[section]?.[key];
    return text || key;
  } catch (error) {
    console.error('Translation error:', error);
    return key;
  }
};

/**
 * Get all translations for a section
 * @param {string} language - 'en' or 'sw'
 * @param {string} section - e.g., 'inventory', 'settings'
 * @returns {object} all translations for section
 */
export const getSectionTranslations = (language, section) => {
  return translations[language]?.[section] || {};
};

export default translations;
